### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by no-e-in** [6502/JSLisp#4]
Is the autocompletion working in editor? How is it activated?
(In **default_keybindings.txt** / EDITOR Bindings there is a cryptic, at least to me, [alt-#191   autocomplete])

**Comment by 6502** [comment]
Autocompletion is triggered by `alt-/` ... I don't know why this is the case but `alt-/` on the browser produces 191 in the `keycode` field of the `keydown` event (both in Chrome and Firefox, not sure about others).

**Comment by no-e-in** [comment]
In the Italian keyboard the symbol `/` is above the 7; so to activate 'autocomplete' I have to press `alt-shift-7`; unfortunately it doesn't work. By changing the layout to ENG keyboard, `alt-/` works.
Is it possible to change the key-binding? (I tried changing, in editor.lisp, ["alt-X" "cut"] to ["alt-X" "autocomplete"] and then `node jslisp.js deploy-html.lisp ide.lisp> ide.html` but without success).

**Comment by 6502** [comment]
The number after "#" is the scan-code. You can find the code for a key openng http://raksy.dyndns.org/keycode.html and typing the characters you want to use. The number that is displayed on keydown is the one you can put after "#" in the configuration file.
Note that there is no need to recompile... just press F1 in the ide; change the file and press OK; changes are applied immediately. You can also save preferred keybindings by logging in (admin/adminpw and then you can create another everyday user).

**Comment by no-e-in** [comment]
Solved, thanks.
